packages:
  - apps/*
  - packages/*

catalogs:
  vue3:
    vue: ^3.5.18
    vite-plugin-vue-devtools: ^7.7.7
    "@vitejs/plugin-vue-jsx": "^5.1.1"

ignoredBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
